from bisect import bisect_left
from collections import defaultdict
from odoo import models, fields, api


class AccountAccount(models.Model):
    _inherit = 'account.account'

    account_type = fields.Selection(
        selection_add=[
            ("asset_inside_advance", "Inside Advances"),
            ("asset_outside_advance", "Outside Advances"),
            ("asset_inventory", "Inventory"),
            ("liability_accrued_liabilities", "Accrued Liabilities"),
            ("liability_accrued_payroll", "Accrued Payroll"),
            ("liability_sales_tax_payable", "Sales Tax Payable"),
            ("liability_taxes_payable", "Taxes Payable"),
            ("asset_other_receivable", "Other Receivables"),
            ("expense_cogs_material", "Cost of Sales Materials"),
            ("expense_cogs_overhead", "Cost of Sales Overhead"),
            ("expense_cogs_salary_wages", "Cost of Sales Salary and Wages"),
            ("expense_cogs_freight", "Cost of Sales Freight"),
            ("expense_sales_fixed", "Sales and Marketing Fixed"),
            ("expense_sales_salary_wages", "Sales and Marketing Salary and Wages"),
            ("expense_sales_variable", "Sales and Marketing Variable"),
            ("expense_sales_travel", "Sales and Marketing Travel"),
            ("expense_sales_occupancy", "Sales and Marketing Occupancy"),
            ("expense_sales_marketing", "Sales and Marketing Marketing"),
            ("expense_sales_other", "Sales and Marketing Other"),
            ("expense_admin_fixed", "General and Administrative Fixed"),
            ("expense_admin_salary_wages", "General and Administrative Salary and Wages"),
            ("expense_admin_variable", "General and Administrative Variable"),
            ("expense_admin_travel", "General and Administrative Travel"),
            ("expense_admin_occupancy", "General and Administrative Occupancy"),
            ("expense_interest", "Interest Expense"),
            ("expense_taxes", "Taxes Expense"),
            ("income_income_interest", "Interest Income"),
            ("income_other_income_expense", "Other Income or Expense"),
            ("expense_type_taxes", "Income Taxes"),
            ("expense_admin_other", "General and Administrative Other"),
            ("expense_gain_loss_sale_assets", "Gain or Loss on Sale of Assets"),
        ],
        ondelete={
            'asset_inside_advance': lambda recs: recs.write({'account_type': 'off_balance'}),
            'asset_outside_advance': lambda recs: recs.write({'account_type': 'off_balance'}),
            'asset_inventory': lambda recs: recs.write({'account_type': 'off_balance'}),
            'liability_accrued_liabilities': lambda recs: recs.write({'account_type': 'off_balance'}),
            'liability_accrued_payroll': lambda recs: recs.write({'account_type': 'off_balance'}),
            'liability_sales_tax_payable': lambda recs: recs.write({'account_type': 'off_balance'}),
            'liability_taxes_payable': lambda recs: recs.write({'account_type': 'off_balance'}),
            'asset_other_receivable': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_cogs_material': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_cogs_overhead': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_cogs_salary_wages': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_cogs_freight': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_sales_fixed': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_sales_salary_wages': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_sales_variable': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_sales_travel': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_sales_occupancy': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_sales_marketing': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_sales_other': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_admin_fixed': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_admin_salary_wages': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_admin_variable': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_admin_travel': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_admin_occupancy': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_interest': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_taxes': lambda recs: recs.write({'account_type': 'off_balance'}),
            'income_income_interest': lambda recs: recs.write({'account_type': 'off_balance'}),
            'income_other_income_expense': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_type_taxes': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_admin_other': lambda recs: recs.write({'account_type': 'off_balance'}),
            'expense_gain_loss_sale_assets': lambda recs: recs.write({'account_type': 'off_balance'}),
        },
    )

    @api.depends('account_type')
    def _compute_include_initial_balance(self):
        for account in self:
            account.include_initial_balance = account.account_type not in (
                # original
                'income',
                'income_other',
                'expense',
                'expense_depreciation',
                'expense_direct_cost',
                'off_balance',
                # added
                'expense_cogs_material',
                'expense_cogs_overhead',
                'expense_cogs_salary_wages',
                'expense_cogs_freight',
                'expense_sales_fixed',
                'expense_sales_salary_wages',
                'expense_sales_variable',
                'expense_sales_travel',
                'expense_sales_occupancy',
                'expense_sales_marketing',
                'expense_sales_other',
                'expense_admin_fixed',
                'expense_admin_salary_wages',
                'expense_admin_variable',
                'expense_admin_travel',
                'expense_admin_occupancy',
                'expense_interest',
                'expense_taxes',
                'income_income_interest',
                'income_other_income_expense',
                'expense_type_taxes',
                'expense_admin_other',
                'expense_gain_loss_sale_assets',
            )
