from . import stock_production_lot
from . import stock_lot_change
from . import stock_lot_note
from . import res_partner
from . import stock_lot_partner
from . import mrp_repair
from . import sale_order
from . import stock_lot_revaluations
from . import stock_lot_hour_log
from . import stock_move_line
